# Generated by Django 6.0 on 2025-12-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_description_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
